title: Sami Ul Haq
description: My Personal Blog
author: SamiU Ul Haq
logo: /hcz-jekyll-blog/static/img/avatar.png
github: https://sami-haq99.github.io/blog/
about: Just another Man

baseurl: ""
url: ""

allowsearch: true

disqus_shortname: sami
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
